### PR TITLE
Only parse the first Content-Type header that's encountered in the loop from bottom to top

### LINKED ISSUE #4: Fails to Parse Body and Attachments if an Extra, Unused Boundary is Present in the Header Lines
(Reproduction in the next comment)

As I was trying to switch an app off an old version of mailparser (that was being used in the browser) I noticed that a handful of emails I was spot checking in our system were not having any content display or attachments show up (neither did they work in the test harness here https://kreata.ee/postal-mime/example/)

As I was debugging it, I noticed the problematic ones all had an extra "Content-Type" and "boundary" declaration somewhere in the header lines that didn't actually seem to be getting used anywhere else (and was in fact listed earlier than the one that was actually used throughout the rest of the file) and the rest of the ones that worked didn't have that.

Via browser DevTools I eventually narrowed it down to this part of the codebase (https://github.com/postalsys/postal-mime/blob/35469512b426e981760eefbefcfc8ce2da20dbe3/src/mime-node.js#L237) where it seemed like what was happening was the extra boundary was getting registered in the loop above as the one Content-Type and boundary to start with (the loop seemed to be going from bottom to top of the headers) but then since it didn't match anything, later on downstream none of the body processing seem to be working (in and around [postal-mime.js::processLine](https://github.com/postalsys/postal-mime/blob/35469512b426e981760eefbefcfc8ce2da20dbe3/src/postal-mime.js#L24))

I'm unsure if these emails are poorly formatted or if this is an expected state, but assuming the latter would definitely be interested in working on a PR for this if I could be pointed in the right direction

### PR DESCRIPTION
**Pull request by sadikinfosec**
Resolves #4

### CODE REVIEW

File: src/mime-node.js [hunk 1]
```diff
@@ -197,11 +197,10 @@ export default class MimeNode {
     }
 
     processHeaders() {
-        for (let i = this.headerLines.length - 1; i >= 0; i--) {
+        for (let i = 0; i <= this.headerLines.length - 1; i++) {
             let line = this.headerLines[i];
             if (i && /^\s/.test(line)) {
-                this.headerLines[i - 1] += '\n' + line;
-                this.headerLines.splice(i, 1);
+                continue;
```
Comment (sadikinfosec) [inline src/mime-node.js:203]: I didn't quite grasp what these 2 lines were for (appending a line of whitespace to the line prior to it?) and wasn't sure how to preserve the behavior easily with the loop's reversed direction

**Comment by andris9** [comment]
The space check thing is MIME line folding, you can read about it [here](https://datatracker.ietf.org/doc/html/rfc5322#section-2.2.3).

With this change, you are not actually fixing much. As per the [RFC grammar](https://www.rfc-editor.org/rfc/rfc2045#section-3) only a single Content-Type header (see the `content` entity in the linked grammar) is allowed. Your change would fix parsing only for these messages you are having problems with. If someone else would send another message with multiple Content-type fields, where these fields are reversed, the parsing would yet again be broken. 

I don't really care which Content-type value is used in the end (as it's invalid anyway) but as this change would probably break line folding I can't accept it as it is. A better fix would to be change [this line](https://github.com/postalsys/postal-mime/blob/35469512b426e981760eefbefcfc8ce2da20dbe3/src/mime-node.js#L215): instead of always setting the `this.contentType` value, check if it isn't already set and if it is, then ignore that new value. This way you'd be keeping the header definition from the bottom.

File: src/mime-node.js (hunk 1 above)
Comment (sadikinfosec) [reply src/mime-node.js:203]: I think I better understand what this was for now after running into an issue without it in the app-side fix I've been trying to make.

Or at least the issue I was hitting was when a line preceeding the Content-Type header starts with whitespace, then nothing gets processed correctly.

So this is actually collapsing lines that start with whitespace onto previous lines so that no lines start with whitespace.

I'll go ahead and split this into 2 loops to do this, so only the 1st one has to operate in reverse direction

**Comment by sadikinfosec** [comment]
> this line

Ah woops just saw this. Thank you a bunch for all that context! 

And yeah that seems much better I can switch to that, thank you for the direction! I went ahead and updated the PR

**Comment by andris9** [comment]
Released as v1.0.13
